Sprint 10 part
Yabrov/java-filmorate pull request #8
Opened 2022-11-30 13:05 UTC by Yabrov

Привет! Сделал сущности иммутабильными, добавил но вые эндпоинты и тесты.

2022-11-30 20:54 UTC, Donald522 requested changes

2022-11-30 20:54 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          this.filmService = filmService;
В lombok есть аннотация `@RequiredArgsConstructor`
Можно добавить ее на класс и не писать boilerplate код конструктора
`@Autowired` не обязателен при единственном конструкторе
Итого будет выглядеть так:

```
@RestController
@RequiredArgsConstructor
public class FilmController {
    private final FilmService filmService;

   // methods
}
```

2022-11-30 20:54 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Iterable<Film> getMostPopularFilms(@RequestParam(defaultValue = "10") Integer count) {
Дефолтное значение лучше убрать в конфигурацию

2022-11-30 20:54 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmNotFoundException.java
> +        super("Film with id=" + filmId + " doesn't exist.");
С одним параметром можно и конкатенацией, но вообще есть `String.format()`
Удобнее:

`String.format("Film with id=%d doesn't exist.", filmId)`

2022-11-30 20:54 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Set<Integer> likes = new HashSet<>();
Я бы здесь хранил просто int
А у пользователя список фильмов, которые он лайкнул.

Что это даст:
Для фильма быстро понимаем кол-во лайков
Для пользователя быстро понимаем фильмы, которые он лайкнул (такого требования сейчас нет, но оно вполне логичное. На ютубе есть вкладка `liked videos`)

Это опционально)

2022-11-30 20:54 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Пользователь с id={} лайкнул фильм '{}'.", user.getId(), film.getName());
Текст в исключении на английском, в логе на русском.
Давай выберем один язык. Лучше английский.

2022-11-30 20:54 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +public interface FilmStorage {
В задании сказали назвать Storage, но вообще более популярное название Repository.
У спринга даже аннотация такая есть.

2022-11-30 20:54 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +public interface UserStorage {
Тоже опционально

У тебя 2 интерфейса Storage отличаются только названиями и типами аргументов.
Можно сделать один generic интерфейс

```
public interface Storage<T> {
  T save(T entity);
  T update (T entity);
  T delete (T entity); // либо T delete (Integer id);
  T findById(Integer id);
  Iterable<T> findAll();
}

public class FilmStorage implements Storage<Film> {
 // ...
}
```

2022-11-30 20:54 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private synchronized Integer getNextId() {
Нет большого смысла делать тут synchronized.
Весь остальной код все равно потоко небезопасный)

2022-11-30 20:54 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/AbstractControllerTest.java
> +@WebMvcTest({FilmController.class, UserController.class})
Это лучше тогда перенести на конкретные тесты.
Смысл абстрактного класса в том, что он содержит общее для всех наследников.

А потом мы добавим еще какой-нибудь MovieController и надо будет добавлять в абстрактный тест

2022-11-30 20:54 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
>  public class UserControllerTest extends AbstractControllerTest {
Классные тесты, я восхитился

2022-11-30 20:56 UTC, Donald522 commented
Привет!

Очень хорошая работа, серьезных замечаний у меня нет.

2022-12-01 08:29 UTC, Yabrov commented
Постарался пройтись по всем замечаниям. Были сомнения на счет оставить int в классе Film, ведь Film финальный класс, помечен @Value, однако структура @AtomicInteger выручила)

2022-12-01 13:47 UTC, Yabrov commented
Также исправил косяк с неправильным восстановлением количества лайков у обновленного фильма, а также списка понравившихся фильмов и друзей у обновленного пользователя. При этом невозможна "накрутка" лайков фильму.

2022-12-01 20:09 UTC, Donald522 requested changes
Привет!
С лайками надо немного поправить, то полкчается, что пользователь может наставить 100500 лайков)

2022-12-01 20:09 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.getLikesCount().incrementAndGet();
Тут получается, что один пользователь может поставить лайк много раз
Надо сделать как-то так
```
boolean added = user.getLikedFilms().add(filmId)
if (added) {
  film.getLikesCount().incrementAndGet();
}
```

2022-12-01 20:09 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +@WebMvcTest({FilmController.class, UserController.class})
Не понял почему у FilmControllerTest оба контроллера в аннотации указаны, а у UserControllerTest ни одного

2022-12-01 20:09 UTC, Donald522 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        user.getLikedFilms().remove(filmId);
И тут тоже, надо проверять успешность удаления из Set

2022-12-02 11:51 UTC, Yabrov commented
Подправил. Однако применять LongAdder не стал, так как он по дефолту в Jackson нет сериализатора для такого типа.

2022-12-02 19:45 UTC, Donald522 approved these changes
Привет!
Теперь ок. Надо было тест написать, когда пользователь ставит лайк дважды на один фильм :)

И про WebMvcTest тоже не понял до конца. Почему не SpringBootTest?
Даже в документации к этой аннотации сказано:
"If you are looking to load your full application configuration and use MockMVC, you should consider [@SpringBootTest](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/context/SpringBootTest.html) combined with [@AutoConfigureMockMvc](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/autoconfigure/web/servlet/AutoConfigureMockMvc.html) rather than this annotation."

https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/autoconfigure/web/servlet/WebMvcTest.html

2022-12-02 19:45 UTC, Donald522 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +@WebMvcTest({FilmController.class, UserController.class})
А почему все-таки не SpringBootTest?

2022-12-03 05:48 UTC, merged